version: "3.9"
services:
    httpdservice1:
        image: 839316227584.dkr.ecr.ap-south-1.amazonaws.com/myrepo:service-1
        ports:
            - "2174:2173"
        networks:
            - my_network
        deploy:
            replicas: 1
            resources:
                limits:
                    cpus: "0.50"
                    memory: 50M
                reservations:
                    cpus: "0.25"
                    memory: 20M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
            update_config:
                parallelism: 1
                delay: 10s
                order: start-first
        environment:
            NODE_ENV: development
            DB_USERNAME: C:\ProgramData\Docker\secrets\dbusername
            DB_PASSWORD: C:\ProgramData\Docker\secrets\dbpassword
        secrets:
            - dbusername
            - dbpassword
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:2173/healthcheck"]
            interval: 10s
            timeout: 3s
            retries: 5

secrets:
    dbusername:
        external: true
    dbpassword:
        external: true

networks:
    my_network:
        external: true
